url: http://shaoweid.github.io
baseurl: /newwebsite/

# Site settings
title: The Claussen Lab
email: jcclauss@iastate.edu
description: "Please contact Prof. Claussen  (jcclauss@iastate.edu) if you are interested in joining the group. We are currently looking for highly motivated postdocs, graduate students, and undergraduate students to join the group."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: cb1a2a
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Suprem Das
  pic: 1
  position: Postdoc
  social:
    - title: envelope
      url: mailto:srdaspurdue@gmail.com
    - title: linkedin
      url: https://www.linkedin.com/pub/suprem-das/26/133/100

- name: Shaowei Ding
  pic: 2
  position: PhD student
  social:
    - title: envelope
      url: mailto:swding@iastate.edu
    - title: linkedin
      url: https://www.linkedin.com/pub/ding-shaowei/46/b79/399
    - title: github
      url: https://github.com/shaoweiD
    - title: myspace
      url: www.shaoweiding.com

- name: Allison Cargill
  pic: 3
  position: MS student
  social:
    - title: envelope
      url: mailto:aacargill@iastate.edu
    - title: linkedin
      url: https://www.linkedin.com/pub/allison-cargill/35/b96/4ab

- name: Bolin Chen
  pic: 4
  position: MS student
  social:
    - title: envelope
      url: mailto:cbl0511@iastate.edu
    - title: linkedin
      url: https://www.linkedin.com/in/bolinchen

- name: Eric Mootz
  pic: 5
  position: Senior, ME
  social:
    - title: envelope
      url: mailto:ejmootz@iastate.edu
    - title: linkedin
      url: https://www.linkedin.com/pub/eric-mootz/63/17a/46a

- name: Jacob Davis
  pic: 6
  position: Junior, ME
  social:
    - title: envelope
      url: mailto:jadavis@iastate.edu
    - title: linkedin
      url: https://www.linkedin.com/pub/jacob-davis/a3/8b0/527

- name: Granit Vokshi
  pic: 7
  position: Junior, ME
  social:
    - title: envelope
      url: mailto:gvokshi@iastate.edu
    - title: linkedin
      url: https://www.linkedin.com/pub/granit-vokshi/a4/a9a/b90

- name: Ashlee Fredericksen
  pic: 8
  position: Junior, ME
  social:
    - title: envelope
      url: mailto:ashleef@iastate.edu
    - title: linkedin
      url: https://www.linkedin.com/pub/ashlee-fredericksen/80/919/63

- name: Anne Leners
  pic: 9
  position: Sophomore, ME
  social:
    - title: envelope
      url: mailto:aleners@iastate.edu
    - title: google-plus
      url: https://plus.google.com/113951348228933739396/about

- name: Andrew Nilles
  pic: 10
  position: Freshman, ME
  social:
    - title: envelope
      url: mailto:asnilles@iastate.edu
    - title: google-plus
      url: https://plus.google.com/114745334590360490433/posts/p/pub

# Alumni 
alumni:
- name: Wyatt Burns
  graduation: B.S Mechanical Engineering, 2014
  social:
    - title: linkedin
      url: https://twitter.com/wyatt_burns

- name: Alumni 2
  graduation: (ISU undergrad)
  social:
    - title: linkedin
      url: https://www.linkedin.com/reg/join?trk=biz-overview-public-join-h

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/dr_jclaussen
  - title: facebook
    url: https://www.facebook.com/ISUMechanicalEngineering
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Iowa State University
  - line: Ames,IA

# Build settings
markdown: kramdown
permalink: pretty
