url: "http://shaoweiD.github.io"
baseurl: /newwebsite/

# Site settings
title: "The Claussen Lab"
email: jcclauss@iastate.edu
description: "Please contact Prof. Claussen  <a href="mailto:jcclauss@iastate.edu">via email</a> if you are interested in joining the group. We are currently looking for highly motivated postdocs, graduate students, and undergraduate students to join the group."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: cb1a2a
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Suprem Das
  pic: 1
  position: Postdoc
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Shaowei Ding
  pic: 2
  position: PhD student
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Allison Cargill
  pic: 3
  position: MS student
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Bolin Chen
  pic: 4
  position: MS student
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Eric Mootz
  pic: 5
  position: Senior, ME
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Jacob Davis
  pic: 6
  position: Junior, ME
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Granit Vokshi
  pic: 7
  position: Junior, ME
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Ashlee Fredericksen
  pic: 8
  position: Junior, ME
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Anne Leners
  pic: 9
  position: Sophomore, ME
  social:
    - title: envelope
      url: mailto:
    - title: linkedin
      url: #

- name: Andrew Nilles
  pic: 10
  position: Freshman, ME
  social:
    - title: envelope
      url: mailto:asnilles@iastate.edu
    - title: google-plus
      url: https://plus.google.com/114745334590360490433/posts/p/pub

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/dr_jclaussen
  - title: facebook
    url: https://www.facebook.com/ISUMechanicalEngineering
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 2104 Black Engineering
  - line: Iowa State University
  - line: Ames,IA

# Build settings
markdown: kramdown
permalink: pretty
